import { LIBRARY_NAME } from "../constant";

export default function cnTemplate() {
    return `// Generated by ${LIBRARY_NAME}
import type { ClassValue } from "@tailwind-config-variants/core";

export function cn(...inputs: ClassValue[]) {
    return inputs.filter(Boolean).join(" ");
}`;
}
