import { LIBRARY_NAME } from "../constant.ts";

export default function cnTemplate() {
    return `// Generated by ${LIBRARY_NAME}
import { extendTailwindMerge } from "tailwind-merge";
import { cx } from "./cx";
import withTCV from "./tailwind-merge-plugin";
import type { ClassValue } from "./types";

const merge = extendTailwindMerge(withTCV);

export function cn(...inputs: ClassValue[]) {
    return merge(cx(...inputs));
}
`;
}
