export default function cvaTemplate() {
    return `// Generated by tailwind-config-variants
import { cn } from "./cn";
import type { ClassValue, VariantMap, Variant } from "./types";

export function cva<V extends VariantMap>({ 
    base, 
    variants, 
    defaultVariants
}: { 
    base: string; 
    variants: V; 
    defaultVariants: Variant<V>;
}) {
    return (variant: Variant<V> = {}, ...className: ClassValue[]) => {
        const classNames = [base];
        for (const key in variants) {
            const variantValue = variant[key]?.toString();
            const defaultValue = defaultVariants[key]?.toString();
            if (variantValue) {
                classNames.push(variants[key][variantValue]);
            } else if (defaultValue) {
                classNames.push(variants[key][defaultValue]);
            }
        }

        return cn(...classNames, ...className);
    };
}`;
}
