import { LIBRARY_NAME } from "../constant.ts";

export default function cvaTemplate() {
    return `// Generated by ${LIBRARY_NAME}
import { cx } from "./cx";
import type { CVA, RecipeConfig, VariantsDefinition } from "./types";
import { createSplitProps, getVariantKeys, getVariantMap } from "./utils";

export function cva<V extends VariantsDefinition>({
    base,
    variants = {} as V,
    defaultVariants = {},
}: RecipeConfig<V>): CVA<V> {
    const cva: CVA<V> = (props = {}, ...className) => {
        const classNames = [base];
        for (const key in variants) {
            const variant = props[key]?.toString();
            const defaultVariant = defaultVariants[key]?.toString();

            if (variant && variant in variants[key]) {
                classNames.push(variants[key][variant]);
            } else if (defaultVariant && defaultVariant in variants[key]) {
                classNames.push(variants[key][defaultVariant]);
            }
        }

        return cx(...classNames, ...className);
    };

    cva.config = { base, variants, defaultVariants };
    cva.variantKeys = getVariantKeys(variants);
    cva.variantMap = getVariantMap(variants);
    cva.splitProps = createSplitProps(variants);

    return cva;
}
`;
}
