import { LIBRARY_NAME } from "../constant.ts";

export default function cxTemplate() {
    return `// Generated by ${LIBRARY_NAME}
import type { ClassValue } from "@tailwind-config-variants/core";

function cx(...inputs: ClassValue[]): string;
function cx() {
    const length = arguments.length;

    let result = "";

    for (let i = 0; i < length; i++) {
        const e = arguments[i];

        if (typeof e === "string") {
            if (result) result += " ";
            result += (result && " ") + e;
        }
    }

    return result;
}

export { type ClassValue, cx };`;
}
