import { camelCase, pascalCase } from "scule";
import type { Recipe, VariantsMap } from "../types";

export default function componentTemplate(name: string, { base, variants, defaultVariants }: Recipe<VariantsMap>) {
    const componentName = camelCase(name);
    const typeName = pascalCase(`${componentName}Variants`);

    return `// Generated by tailwind-config-variants
import { cva } from "./cva";

const ${componentName} = cva(${JSON.stringify(
        {
            base,
            variants,
            defaultVariants,
        },
        null,
        4,
    )});

export type ${typeName} = Parameters<typeof ${componentName}>[0];

export default ${componentName};`;
}
