import { camelCase, pascalCase } from "scule";
import type { RecipeData } from "../builder/context.ts";
import { LIBRARY_NAME } from "../constant.ts";

export default function recipeTemplate({ name, type, definition }: RecipeData) {
    const variableName = camelCase(name);
    const typeName = pascalCase(`${name}Variants`);

    return `// Generated by ${LIBRARY_NAME}
import type { RecipeVariantProps } from "@tailwind-config-variants/core";
import { ${type} } from "../${type}";

const ${variableName} = ${type}(${JSON.stringify(definition, null, 4)});

export default ${variableName};
export type ${typeName} = RecipeVariantProps<typeof ${variableName}>;
`;
}
