import { camelCase, pascalCase } from "scule";
import { LIBRARY_NAME } from "../constant.ts";
import type { SlotRecipe } from "../types";

export default function slotRecipeTemplate(name: string, recipe: SlotRecipe) {
    const variableName = camelCase(name);
    const typeName = pascalCase(`${name}Variants`);

    return `// Generated by ${LIBRARY_NAME}
import type { RecipeVariantProps } from "@tailwind-config-variants/core";
import { createSplitProps, getVariantKeys, getVariantMap } from "@tailwind-config-variants/core";
import { sva } from "../sva";

const config = ${JSON.stringify(recipe, null, 4)} as const;

const ${variableName} = sva(config);

const splitProps = createSplitProps(config.variants);

const variantKeys = getVariantKeys(config.variants);
const variantMap = getVariantMap(config.variants);

export default ${variableName};
export type ${typeName} = RecipeVariantProps<typeof ${variableName}>;

export { ${variableName} as recipe, config, splitProps, variantKeys, variantMap };
`;
}
