import { pascalCase } from "scule";
import type { SlotRecipe } from "../types";

export default function slotRecipeTemplate(name: string, recipe: SlotRecipe) {
    const typeName = pascalCase(`${name}Variants`);

    return `// Generated by tailwind-config-variants
import type { RecipeVariantProps } from "@tailwind-config-variants/core";
import { createSplitProps, getVariantKeys, getVariantMap } from "@tailwind-config-variants/core";
import { sva } from "../sva";

const config = ${JSON.stringify(recipe, null, 4)} as const;

const ${name} = sva(config);

const splitProps = createSplitProps(config.variants);

const variantKeys = getVariantKeys(config.variants);
const variantMap = getVariantMap(config.variants);

export default ${name};
export type ${typeName} = RecipeVariantProps<typeof ${name}>;

export { ${name} as recipe, config, splitProps, variantKeys, variantMap };
`;
}
