import { pascalCase } from "scule";
import type { SlotRecipe } from "../types";

export default function slotRecipeTemplate(name: string, recipe: SlotRecipe) {
    const typeName = pascalCase(`${name}Variants`);

    return `// Generated by tailwind-config-variants
import { sva } from "../sva";

const ${name} = sva(${JSON.stringify(recipe, null, 4)});

export type ${typeName} = NonNullable<Parameters<typeof ${name}>[0]>;

export default ${name};`;
}
