import { LIBRARY_NAME } from "../constant.ts";

export default function svaTemplate() {
    return `// Generated by ${LIBRARY_NAME}
import { cx } from "./cx";
import type { SlotRecipe, SlotVariantsDefinition, SVA } from "./types";
import { createSplitProps, getVariantKeys, getVariantMap } from "./utils";

export function sva<S extends string, SV extends SlotVariantsDefinition<S>>({
    base,
    variants = {} as SV,
    defaultVariants = {},
}: SlotRecipe<S, SV>): SVA<S, SV> {
    const sva: SVA<S, SV> = (variant = {}) => {
        const slotClassNames = {} as Record<S, (string | undefined)[]>;
        for (const slot in base) {
            slotClassNames[slot] = [base[slot]];
        }
        for (const key in variants) {
            for (const slot in base) {
                const variantValue = variant[key]?.toString();
                const defaultValue = defaultVariants[key]?.toString();
                if (variantValue) {
                    slotClassNames[slot].push(variants[key][variantValue][slot]);
                } else if (defaultValue) {
                    slotClassNames[slot].push(variants[key][defaultValue][slot]);
                }
            }
        }

        const result = {} as ReturnType<SVA<S, SV>>;
        for (const slot in slotClassNames) {
            result[slot] = (...className) => cx(...slotClassNames[slot], ...className);
        }

        return result;
    };

    sva.config = { base, variants, defaultVariants };
    sva.variantKeys = getVariantKeys(variants);
    sva.variantMap = getVariantMap(variants);
    sva.splitProps = createSplitProps(variants);

    return sva;
}
`;
}
