export default function svaTemplate() {
    return `// Generated by tailwind-config-variants
import type {  ClassValue, SlotVariant, SlotVariantMap } from "@tailwind-config-variants/core";
import { cn } from "./cn";

export function sva<S extends string, SV extends SlotVariantMap<S>>({ 
    base,
    variants,
    defaultVariants
}: { 
    base: Record<S, string>; 
    variants: SV;
    defaultVariants: SlotVariant<SV>;
}) {
    const splitProps = <P extends SlotVariant<SV>>(props: P): [Pick<P, keyof SV>, Omit<P, keyof SV>] => {
        const variantProps = {} as P;
        const otherProps = {} as P
        for (const key in props) {
            if (Object.hasOwn(variants, key)) variantProps[key] = props[key];
            else otherProps[key] = props[key];
        }
        return [variantProps, otherProps] as const;
    }


    return Object.assign((variant: SlotVariant<SV> = {}) => {
        const slotClassNames = {} as Record<S, (string | undefined)[]>;
        for (const slot in base) {
            slotClassNames[slot] = [base[slot]];
        }
        for (const key in variants) {
            for (const slot in base) {
                const variantValue = variant[key]?.toString();
                const defaultValue = defaultVariants?.[key]?.toString();
                if (variantValue) {
                    slotClassNames[slot].push(variants[key][variantValue][slot]);
                } else if (defaultValue) {
                    slotClassNames[slot].push(variants[key][defaultValue][slot]);
                }
            }
        }

        const result = {} as { [K in S]: (...className: ClassValue[]) => string };
        for (const slot in slotClassNames) {
            result[slot] = (...className: ClassValue[]) => cn(...slotClassNames[slot], ...className);
        }
        
        return result;
    }, { splitProps });
}`;
}
