import type { GroupsData } from "../builder/context.ts";
import { LIBRARY_NAME } from "../constant.ts";

export default function tailwindMergeTemplate(groups: GroupsData) {
    const groupsObject = Object.fromEntries(groups);

    return `// Generated by ${LIBRARY_NAME}
import { type Config, mergeConfigs } from 'tailwind-merge'

function withTCV(config: Config<string, string>) {
    return mergeConfigs<TCVClassGroups>(config, ${JSON.stringify({ extend: { classGroups: groupsObject } }, null, 4)})
}

export default withTCV;
export type TCVClassGroups = "${Object.keys(groupsObject).join('" | "')}";
`;
}
