import type { ComponentData } from "../builder/context.ts";
import { LIBRARY_NAME } from "../constant.ts";

export default function tailwindTemplate(components: ComponentData[], content: string[]) {
    return `// Generated by ${LIBRARY_NAME}
import plugin from "tailwindcss/plugin";

const COMPONENTS = ${JSON.stringify(components, null, 4)};

const tailwindConfigVariants = plugin(api => {
    COMPONENTS.forEach((component) => {
        api.addComponents({
            [\`.\${component.className}\`]: typeof component.styles === "string" 
                ? { [\`@apply \${component.styles}\`]: {} }
                : component.styles 
        });
    });
}, {
    content: ${JSON.stringify(content, null, 4)}
});

export default tailwindConfigVariants;
`;
}
