import type { ComponentData } from "../builder/context.ts";
import { LIBRARY_NAME } from "../constant.ts";

export default function tailwindTemplate(components: ComponentData[], content: string[]) {
    return `// Generated by ${LIBRARY_NAME}
import plugin from "tailwindcss/plugin";

const tailwindConfigVariants = plugin(api => {
    api.addComponents({
${components
    .map(
        ({ className, styles }) =>
            `\t\t".${className}": ${JSON.stringify(typeof styles === "string" ? { [`@apply ${styles}`]: {} } : styles)}`,
    )
    .join(",\n")}
});
}, {
    content: ${JSON.stringify(content, null, 4)}
});

export default tailwindConfigVariants;
`;
}
