export default function tailwindTemplate(components: Array<{ className: string; styles: string }>) {
    return `// Generated by tailwind-config-variants
import plugin from "tailwindcss/plugin";

const COMPONENTS = ${JSON.stringify(components, null, 4)};

export default plugin(api => {
    COMPONENTS.forEach((component) => {
        api.addComponents({
            [\`.\${component.className}\`]: {
                [\`@apply \${component.styles}\`]: {}
            }
        });
    });
});
`;
}
